language: python

env:
  global:
    - DISPLAY=":99.0"

services:
  - xvfb

jobs:
  include:
    - os: linux
      env: PYTHON_VERSION="3.7" BENCHMARK=1
    - os: linux
      env: PYTHON_VERSION="3.8"

before_install:
  - sudo -E apt-add-repository -y "ppa:ubuntu-toolchain-r/test"
  - sudo apt-get -q update
  - sudo -E apt-get -yq --no-install-suggests --no-install-recommends $(travis_apt_get_options) install libxkbcommon-x11-0
  - wget "http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh" -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"

install:
  - conda install -y python=$PYTHON_VERSION
  - python --version
  - pip install -e .[test]

before_script:
  - /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1400x900x24
  - sleep 3

script:
  - pytest foamgraph/tests
  - if [[ "$BENCHMARK" == 1 ]]; then bash benchmarks/run; fi
